name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "533cab360eded62c2bd7deb56ee460ad8144ea49a1fd64028c2570252d82d715"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
